
/**
 * Auto-generated spec predicates
 */
import csharp

predicate isLLMSource(Method m) {
  false
  or (m.getDeclaringType().getNamespace().getName() = "Reflection" and m.getDeclaringType().getName() = "Assembly" and m.getName() = "GetType" and m.getStringSignature().matches("%Type GetType(String name)%")) // item 1 role=source
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<Byte>" and m.getName() = "AddRange" and m.getStringSignature().matches("%Void AddRange(IEnumerable<Byte> collection)%")) // item 120 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<Byte>" and m.getName() = "AddRange" and m.getStringSignature().matches("%Void AddRange(IEnumerable<Byte> collection)%")) // item 121 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<Byte>" and m.getName() = "AddRange" and m.getStringSignature().matches("%Void AddRange(IEnumerable<Byte> collection)%")) // item 122 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<Byte>" and m.getName() = "AddRange" and m.getStringSignature().matches("%Void AddRange(IEnumerable<Byte> collection)%")) // item 123 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<Byte>" and m.getName() = "AddRange" and m.getStringSignature().matches("%Void AddRange(IEnumerable<Byte> collection)%")) // item 124 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "HashSet<String>" and m.getName() = "Add" and m.getStringSignature().matches("%Boolean Add(String item)%")) // item 126 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "HashSet<String>" and m.getName() = "Add" and m.getStringSignature().matches("%Boolean Add(String item)%")) // item 127 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "HashSet<String>" and m.getName() = "Add" and m.getStringSignature().matches("%Boolean Add(String item)%")) // item 128 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "HashSet<String>" and m.getName() = "Add" and m.getStringSignature().matches("%Boolean Add(String item)%")) // item 129 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<AggregationManifestEntry>" and m.getName() = "Find" and m.getStringSignature().matches("%AggregationManifestEntry Find(Predicate<AggregationManifestEntry> match)%")) // item 141 role=source
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<AggregationManifestEntry>" and m.getName() = "AddRange" and m.getStringSignature().matches("%Void AddRange(IEnumerable<AggregationManifestEntry> collection)%")) // item 142 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<SceneSettings>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(SceneSettings item)%")) // item 144 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<SceneSettings>" and m.getName() = "Find" and m.getStringSignature().matches("%SceneSettings Find(Predicate<SceneSettings> match)%")) // item 146 role=source
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<SceneSettings>" and m.getName() = "Find" and m.getStringSignature().matches("%SceneSettings Find(Predicate<SceneSettings> match)%")) // item 147 role=source
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<SceneSettings>" and m.getName() = "Find" and m.getStringSignature().matches("%SceneSettings Find(Predicate<SceneSettings> match)%")) // item 148 role=source
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<SceneSettings>" and m.getName() = "Find" and m.getStringSignature().matches("%SceneSettings Find(Predicate<SceneSettings> match)%")) // item 149 role=source
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<<unknown type>>" and m.getName() = "Find" and m.getStringSignature().matches("%<unknown type> Find(Predicate<<unknown type>> match)%")) // item 192 role=source
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<<unknown type>>" and m.getName() = "Find" and m.getStringSignature().matches("%<unknown type> Find(Predicate<<unknown type>> match)%")) // item 193 role=source
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<<unknown type>>" and m.getName() = "AddRange" and m.getStringSignature().matches("%Void AddRange(IEnumerable<<unknown type>> collection)%")) // item 195 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<<unknown type>>" and m.getName() = "AddRange" and m.getStringSignature().matches("%Void AddRange(IEnumerable<<unknown type>> collection)%")) // item 196 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<<unknown type>>" and m.getName() = "AddRange" and m.getStringSignature().matches("%Void AddRange(IEnumerable<<unknown type>> collection)%")) // item 197 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<<unknown type>>" and m.getName() = "ToArray" and m.getStringSignature().matches("%GameObject[] ToArray()%")) // item 198 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<<unknown type>>" and m.getName() = "ToArray" and m.getStringSignature().matches("%GameObject[] ToArray()%")) // item 199 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<<unknown type>>" and m.getName() = "ToArray" and m.getStringSignature().matches("%GameObject[] ToArray()%")) // item 200 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<<unknown type>>" and m.getName() = "ToArray" and m.getStringSignature().matches("%GameObject[] ToArray()%")) // item 201 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<<unknown type>>" and m.getName() = "ToArray" and m.getStringSignature().matches("%Transform[] ToArray()%")) // item 202 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<<unknown type>>" and m.getName() = "ToArray" and m.getStringSignature().matches("%Object[] ToArray()%")) // item 203 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<<unknown type>>" and m.getName() = "ToArray" and m.getStringSignature().matches("%Object[] ToArray()%")) // item 204 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<<unknown type>>" and m.getName() = "ToArray" and m.getStringSignature().matches("%Object[] ToArray()%")) // item 205 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<<unknown type>>" and m.getName() = "ToArray" and m.getStringSignature().matches("%MeshPrimitive[] ToArray()%")) // item 206 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<Entry>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(Entry item)%")) // item 212 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<Entry>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(Entry item)%")) // item 213 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<Entry>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(Entry item)%")) // item 214 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<Entry>" and m.getName() = "Find" and m.getStringSignature().matches("%Entry Find(Predicate<Entry> match)%")) // item 215 role=source
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<DynamicObject>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(DynamicObject item)%")) // item 227 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<DynamicObject>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(DynamicObject item)%")) // item 228 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<DynamicObject>" and m.getName() = "Contains" and m.getStringSignature().matches("%Boolean Contains(DynamicObject item)%")) // item 229 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<DynamicObjectIdPool>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(DynamicObjectIdPool item)%")) // item 230 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<DynamicObjectIdPool>" and m.getName() = "Contains" and m.getStringSignature().matches("%Boolean Contains(DynamicObjectIdPool item)%")) // item 231 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<DashboardObject>" and m.getName() = "Find" and m.getStringSignature().matches("%DashboardObject Find(Predicate<DashboardObject> match)%")) // item 233 role=source
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<DashboardObject>" and m.getName() = "AddRange" and m.getStringSignature().matches("%Void AddRange(IEnumerable<DashboardObject> collection)%")) // item 234 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<EditorWebRequest>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(EditorWebRequest item)%")) // item 235 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<EditorWebRequest>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(EditorWebRequest item)%")) // item 236 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<EditorWebRequest>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(EditorWebRequest item)%")) // item 237 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "Queue<EditorWebRequest>" and m.getName() = "Enqueue" and m.getStringSignature().matches("%Void Enqueue(EditorWebRequest item)%")) // item 239 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "Queue<EditorWebRequest>" and m.getName() = "Dequeue" and m.getStringSignature().matches("%EditorWebRequest Dequeue()%")) // item 240 role=source
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "Dictionary<<unknown type>,Int32>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(<unknown type> key, Int32 value)%")) // item 241 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "Dictionary<<unknown type>,Int32>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(<unknown type> key, Int32 value)%")) // item 242 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<BakeableMesh>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(BakeableMesh item)%")) // item 243 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<BakeableMesh>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(BakeableMesh item)%")) // item 244 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<BakeableMesh>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(BakeableMesh item)%")) // item 245 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<BakeableMesh>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(BakeableMesh item)%")) // item 246 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<BakeableMesh>" and m.getName() = "Find" and m.getStringSignature().matches("%BakeableMesh Find(Predicate<BakeableMesh> match)%")) // item 249 role=source
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<BakeableMesh>" and m.getName() = "Find" and m.getStringSignature().matches("%BakeableMesh Find(Predicate<BakeableMesh> match)%")) // item 250 role=source
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<SceneVersion>" and m.getName() = "Find" and m.getStringSignature().matches("%SceneVersion Find(Predicate<SceneVersion> match)%")) // item 253 role=source
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "Dictionary<PrimKey,<unknown type>>" and m.getName() = "TryGetValue" and m.getStringSignature().matches("%Boolean TryGetValue(<unknown type> value, PrimKey key)%")) // item 257 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "Dictionary<<unknown type>,MeshPrimitive[]>" and m.getName() = "TryGetValue" and m.getStringSignature().matches("%Boolean TryGetValue(<unknown type> key, MeshPrimitive[] value)%")) // item 258 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "Dictionary<String,ShaderPropertyCollection>" and m.getName() = "TryGetValue" and m.getStringSignature().matches("%Boolean TryGetValue(ShaderPropertyCollection value, String key)%")) // item 260 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "Queue<DynamicObjectForm>" and m.getName() = "Dequeue" and m.getStringSignature().matches("%DynamicObjectForm Dequeue()%")) // item 262 role=source
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<DynamicSortable>" and m.getName() = "Find" and m.getStringSignature().matches("%DynamicSortable Find(Predicate<DynamicSortable> match)%")) // item 277 role=source
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<DynamicSortable>" and m.getName() = "Find" and m.getStringSignature().matches("%DynamicSortable Find(Predicate<DynamicSortable> match)%")) // item 278 role=source
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<DynamicSortable>" and m.getName() = "Sort" and m.getStringSignature().matches("%Void Sort(Comparison<DynamicSortable> comparison)%")) // item 282 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<DynamicSortable>" and m.getName() = "Sort" and m.getStringSignature().matches("%Void Sort(Comparison<DynamicSortable> comparison)%")) // item 283 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<DynamicSortable>" and m.getName() = "Sort" and m.getStringSignature().matches("%Void Sort(Comparison<DynamicSortable> comparison)%")) // item 284 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<Fixation>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(Fixation item)%")) // item 285 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<Fixation>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(Fixation item)%")) // item 286 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<SensorDataPoint>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(SensorDataPoint item)%")) // item 289 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<ButtonState>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(ButtonState item)%")) // item 294 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<ButtonState>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(ButtonState item)%")) // item 295 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<ButtonState>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(ButtonState item)%")) // item 296 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<ButtonState>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(ButtonState item)%")) // item 297 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<ButtonState>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(ButtonState item)%")) // item 298 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<ButtonState>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(ButtonState item)%")) // item 299 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<ButtonState>" and m.getName() = "Find" and m.getStringSignature().matches("%ButtonState Find(Predicate<ButtonState> match)%")) // item 302 role=source
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<ButtonState>" and m.getName() = "Find" and m.getStringSignature().matches("%ButtonState Find(Predicate<ButtonState> match)%")) // item 303 role=source
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<ButtonState>" and m.getName() = "Find" and m.getStringSignature().matches("%ButtonState Find(Predicate<ButtonState> match)%")) // item 304 role=source
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<ButtonState>" and m.getName() = "Find" and m.getStringSignature().matches("%ButtonState Find(Predicate<ButtonState> match)%")) // item 305 role=source
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "Dictionary<String,ButtonState>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(ButtonState value, String key)%")) // item 306 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "Queue<DynamicObjectSnapshot>" and m.getName() = "Enqueue" and m.getStringSignature().matches("%Void Enqueue(DynamicObjectSnapshot item)%")) // item 450 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "Queue<DynamicObjectSnapshot>" and m.getName() = "Dequeue" and m.getStringSignature().matches("%DynamicObjectSnapshot Dequeue()%")) // item 451 role=source
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "HashSet<<unknown type>>" and m.getName() = "Add" and m.getStringSignature().matches("%Boolean Add(<unknown type> item)%")) // item 452 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "HashSet<<unknown type>>" and m.getName() = "Add" and m.getStringSignature().matches("%Boolean Add(<unknown type> item)%")) // item 453 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<AssessmentBase>" and m.getName() = "Insert" and m.getStringSignature().matches("%Void Insert(AssessmentBase item, Int32 index)%")) // item 467 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<AssessmentBase>" and m.getName() = "Remove" and m.getStringSignature().matches("%Boolean Remove(AssessmentBase item)%")) // item 468 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<AssessmentBase>" and m.getName() = "Remove" and m.getStringSignature().matches("%Boolean Remove(AssessmentBase item)%")) // item 469 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<AssessmentBase>" and m.getName() = "Find" and m.getStringSignature().matches("%AssessmentBase Find(Predicate<AssessmentBase> match)%")) // item 470 role=source
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<GrabComponentsRequired>" and m.getName() = "Contains" and m.getStringSignature().matches("%Boolean Contains(GrabComponentsRequired item)%")) // item 471 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<HMDFocusButton>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(HMDFocusButton item)%")) // item 472 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<KeyValuePair<String,Object>>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(KeyValuePair<String,Object> item)%")) // item 473 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<KeyValuePair<String,Object>>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(KeyValuePair<String,Object> item)%")) // item 474 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<KeyValuePair<String,Object>>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(KeyValuePair<String,Object> item)%")) // item 475 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<KeyValuePair<String,Object>>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(KeyValuePair<String,Object> item)%")) // item 476 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "Append" and m.getStringSignature().matches("%StringBuilder Append(String value)%")) // item 499 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "Append" and m.getStringSignature().matches("%StringBuilder Append(String value)%")) // item 500 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "Append" and m.getStringSignature().matches("%StringBuilder Append(String value)%")) // item 501 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "Append" and m.getStringSignature().matches("%StringBuilder Append(String value)%")) // item 502 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "Append" and m.getStringSignature().matches("%StringBuilder Append(String value)%")) // item 503 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "Append" and m.getStringSignature().matches("%StringBuilder Append(String value)%")) // item 504 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "Append" and m.getStringSignature().matches("%StringBuilder Append(String value)%")) // item 505 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "Append" and m.getStringSignature().matches("%StringBuilder Append(String value)%")) // item 506 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "Append" and m.getStringSignature().matches("%StringBuilder Append(Object value)%")) // item 579 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "Append" and m.getStringSignature().matches("%StringBuilder Append(Object value)%")) // item 580 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "Append" and m.getStringSignature().matches("%StringBuilder Append(Object value)%")) // item 581 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "Append" and m.getStringSignature().matches("%StringBuilder Append(Object value)%")) // item 582 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "Append" and m.getStringSignature().matches("%StringBuilder Append(Object value)%")) // item 583 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "Append" and m.getStringSignature().matches("%StringBuilder Append(Object value)%")) // item 584 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "AppendLine" and m.getStringSignature().matches("%StringBuilder AppendLine(String value)%")) // item 585 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "AppendLine" and m.getStringSignature().matches("%StringBuilder AppendLine(String value)%")) // item 586 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "Directory" and m.getName() = "CreateDirectory" and m.getStringSignature().matches("%DirectoryInfo CreateDirectory(String path)%")) // item 739 role=source
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "Directory" and m.getName() = "CreateDirectory" and m.getStringSignature().matches("%DirectoryInfo CreateDirectory(String path)%")) // item 740 role=source
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "Directory" and m.getName() = "CreateDirectory" and m.getStringSignature().matches("%DirectoryInfo CreateDirectory(String path)%")) // item 741 role=source
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "Directory" and m.getName() = "CreateDirectory" and m.getStringSignature().matches("%DirectoryInfo CreateDirectory(String path)%")) // item 742 role=source
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "Path" and m.getName() = "Combine" and m.getStringSignature().matches("%String Combine(String path1, String path2)%")) // item 816 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "Path" and m.getName() = "Combine" and m.getStringSignature().matches("%String Combine(String path1, String path2)%")) // item 817 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "Path" and m.getName() = "Combine" and m.getStringSignature().matches("%String Combine(String path1, String path2)%")) // item 818 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "Path" and m.getName() = "Combine" and m.getStringSignature().matches("%String Combine(String path1, String path2)%")) // item 819 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "Path" and m.getName() = "GetFileName" and m.getStringSignature().matches("%String GetFileName(String path)%")) // item 820 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "Path" and m.getName() = "GetFileName" and m.getStringSignature().matches("%String GetFileName(String path)%")) // item 821 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "Path" and m.getName() = "GetFileName" and m.getStringSignature().matches("%String GetFileName(String path)%")) // item 822 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "StreamReader" and m.getName() = "ReadLine" and m.getStringSignature().matches("%String ReadLine()%")) // item 827 role=source
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "StreamReader" and m.getName() = "ReadLine" and m.getStringSignature().matches("%String ReadLine()%")) // item 828 role=source
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "StreamReader" and m.getName() = "ReadLine" and m.getStringSignature().matches("%String ReadLine()%")) // item 829 role=source
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "StreamReader" and m.getName() = "ReadLine" and m.getStringSignature().matches("%String ReadLine()%")) // item 830 role=source
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "StreamReader" and m.getName() = "ReadLine" and m.getStringSignature().matches("%String ReadLine()%")) // item 831 role=source
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "StreamReader" and m.getName() = "ReadLine" and m.getStringSignature().matches("%String ReadLine()%")) // item 832 role=source
  or (m.getDeclaringType().getNamespace().getName() = "RegularExpressions" and m.getDeclaringType().getName() = "Regex" and m.getName() = "Replace" and m.getStringSignature().matches("%String Replace(String input, String pattern, String replacement)%")) // item 886 role=taint-propagator
}

predicate isLLMSink(Method m) {
  false
  or (m.getDeclaringType().getNamespace().getName() = "Reflection" and m.getDeclaringType().getName() = "FieldInfo" and m.getName() = "GetValue" and m.getStringSignature().matches("%Object GetValue(Object obj)%")) // item 4 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "Reflection" and m.getDeclaringType().getName() = "FieldInfo" and m.getName() = "SetValue" and m.getStringSignature().matches("%Void SetValue(Object obj, Object value)%")) // item 5 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "Reflection" and m.getDeclaringType().getName() = "FieldInfo" and m.getName() = "SetValue" and m.getStringSignature().matches("%Void SetValue(Object obj, Object value)%")) // item 6 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "InteropServices" and m.getDeclaringType().getName() = "Marshal" and m.getName() = "PtrToStructure" and m.getStringSignature().matches("%Object PtrToStructure(IntPtr ptr, Type structureType)%")) // item 7 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "Collections" and m.getDeclaringType().getName() = "BitArray" and m.getName() = "CopyTo" and m.getStringSignature().matches("%Void CopyTo(Array array, Int32 index)%")) // item 8 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<Byte>" and m.getName() = "AddRange" and m.getStringSignature().matches("%Void AddRange(IEnumerable<Byte> collection)%")) // item 120 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<Byte>" and m.getName() = "AddRange" and m.getStringSignature().matches("%Void AddRange(IEnumerable<Byte> collection)%")) // item 121 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<Byte>" and m.getName() = "AddRange" and m.getStringSignature().matches("%Void AddRange(IEnumerable<Byte> collection)%")) // item 122 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<Byte>" and m.getName() = "AddRange" and m.getStringSignature().matches("%Void AddRange(IEnumerable<Byte> collection)%")) // item 123 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<Byte>" and m.getName() = "AddRange" and m.getStringSignature().matches("%Void AddRange(IEnumerable<Byte> collection)%")) // item 124 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "HashSet<String>" and m.getName() = "Add" and m.getStringSignature().matches("%Boolean Add(String item)%")) // item 126 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "HashSet<String>" and m.getName() = "Add" and m.getStringSignature().matches("%Boolean Add(String item)%")) // item 127 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "HashSet<String>" and m.getName() = "Add" and m.getStringSignature().matches("%Boolean Add(String item)%")) // item 128 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "HashSet<String>" and m.getName() = "Add" and m.getStringSignature().matches("%Boolean Add(String item)%")) // item 129 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<AggregationManifestEntry>" and m.getName() = "AddRange" and m.getStringSignature().matches("%Void AddRange(IEnumerable<AggregationManifestEntry> collection)%")) // item 142 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<SceneSettings>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(SceneSettings item)%")) // item 144 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<<unknown type>>" and m.getName() = "AddRange" and m.getStringSignature().matches("%Void AddRange(IEnumerable<<unknown type>> collection)%")) // item 195 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<<unknown type>>" and m.getName() = "AddRange" and m.getStringSignature().matches("%Void AddRange(IEnumerable<<unknown type>> collection)%")) // item 196 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<<unknown type>>" and m.getName() = "AddRange" and m.getStringSignature().matches("%Void AddRange(IEnumerable<<unknown type>> collection)%")) // item 197 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<<unknown type>>" and m.getName() = "ToArray" and m.getStringSignature().matches("%GameObject[] ToArray()%")) // item 198 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<<unknown type>>" and m.getName() = "ToArray" and m.getStringSignature().matches("%GameObject[] ToArray()%")) // item 199 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<<unknown type>>" and m.getName() = "ToArray" and m.getStringSignature().matches("%GameObject[] ToArray()%")) // item 200 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<<unknown type>>" and m.getName() = "ToArray" and m.getStringSignature().matches("%GameObject[] ToArray()%")) // item 201 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<<unknown type>>" and m.getName() = "ToArray" and m.getStringSignature().matches("%Transform[] ToArray()%")) // item 202 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<<unknown type>>" and m.getName() = "ToArray" and m.getStringSignature().matches("%Object[] ToArray()%")) // item 203 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<<unknown type>>" and m.getName() = "ToArray" and m.getStringSignature().matches("%Object[] ToArray()%")) // item 204 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<<unknown type>>" and m.getName() = "ToArray" and m.getStringSignature().matches("%Object[] ToArray()%")) // item 205 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<<unknown type>>" and m.getName() = "ToArray" and m.getStringSignature().matches("%MeshPrimitive[] ToArray()%")) // item 206 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<Entry>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(Entry item)%")) // item 212 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<Entry>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(Entry item)%")) // item 213 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<Entry>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(Entry item)%")) // item 214 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<Entry>" and m.getName() = "Sort" and m.getStringSignature().matches("%Void Sort(Comparison<Entry> comparison)%")) // item 220 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<Entry>" and m.getName() = "Sort" and m.getStringSignature().matches("%Void Sort(Comparison<Entry> comparison)%")) // item 221 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<Entry>" and m.getName() = "Sort" and m.getStringSignature().matches("%Void Sort(Comparison<Entry> comparison)%")) // item 222 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<Entry>" and m.getName() = "Sort" and m.getStringSignature().matches("%Void Sort(Comparison<Entry> comparison)%")) // item 223 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<DynamicObject>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(DynamicObject item)%")) // item 224 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<DynamicObject>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(DynamicObject item)%")) // item 225 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<DynamicObject>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(DynamicObject item)%")) // item 226 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<DynamicObject>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(DynamicObject item)%")) // item 227 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<DynamicObject>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(DynamicObject item)%")) // item 228 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<DynamicObject>" and m.getName() = "Contains" and m.getStringSignature().matches("%Boolean Contains(DynamicObject item)%")) // item 229 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<DynamicObjectIdPool>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(DynamicObjectIdPool item)%")) // item 230 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<DynamicObjectIdPool>" and m.getName() = "Contains" and m.getStringSignature().matches("%Boolean Contains(DynamicObjectIdPool item)%")) // item 231 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<DashboardObject>" and m.getName() = "AddRange" and m.getStringSignature().matches("%Void AddRange(IEnumerable<DashboardObject> collection)%")) // item 234 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<EditorWebRequest>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(EditorWebRequest item)%")) // item 235 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<EditorWebRequest>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(EditorWebRequest item)%")) // item 236 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<EditorWebRequest>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(EditorWebRequest item)%")) // item 237 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "Queue<EditorWebRequest>" and m.getName() = "Enqueue" and m.getStringSignature().matches("%Void Enqueue(EditorWebRequest item)%")) // item 239 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "Dictionary<<unknown type>,Int32>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(<unknown type> key, Int32 value)%")) // item 241 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "Dictionary<<unknown type>,Int32>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(<unknown type> key, Int32 value)%")) // item 242 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<BakeableMesh>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(BakeableMesh item)%")) // item 243 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<BakeableMesh>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(BakeableMesh item)%")) // item 244 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<BakeableMesh>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(BakeableMesh item)%")) // item 245 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<BakeableMesh>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(BakeableMesh item)%")) // item 246 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "Dictionary<PrimKey,<unknown type>>" and m.getName() = "TryGetValue" and m.getStringSignature().matches("%Boolean TryGetValue(<unknown type> value, PrimKey key)%")) // item 257 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "Dictionary<<unknown type>,MeshPrimitive[]>" and m.getName() = "TryGetValue" and m.getStringSignature().matches("%Boolean TryGetValue(<unknown type> key, MeshPrimitive[] value)%")) // item 258 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "Dictionary<String,ShaderPropertyCollection>" and m.getName() = "TryGetValue" and m.getStringSignature().matches("%Boolean TryGetValue(ShaderPropertyCollection value, String key)%")) // item 260 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<DynamicSortable>" and m.getName() = "Sort" and m.getStringSignature().matches("%Void Sort(Comparison<DynamicSortable> comparison)%")) // item 282 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<DynamicSortable>" and m.getName() = "Sort" and m.getStringSignature().matches("%Void Sort(Comparison<DynamicSortable> comparison)%")) // item 283 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<DynamicSortable>" and m.getName() = "Sort" and m.getStringSignature().matches("%Void Sort(Comparison<DynamicSortable> comparison)%")) // item 284 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<Fixation>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(Fixation item)%")) // item 285 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<Fixation>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(Fixation item)%")) // item 286 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<SensorDataPoint>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(SensorDataPoint item)%")) // item 289 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<ButtonState>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(ButtonState item)%")) // item 294 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<ButtonState>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(ButtonState item)%")) // item 295 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<ButtonState>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(ButtonState item)%")) // item 296 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<ButtonState>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(ButtonState item)%")) // item 297 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<ButtonState>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(ButtonState item)%")) // item 298 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<ButtonState>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(ButtonState item)%")) // item 299 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "Dictionary<String,ButtonState>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(ButtonState value, String key)%")) // item 306 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "Queue<DynamicObjectSnapshot>" and m.getName() = "Enqueue" and m.getStringSignature().matches("%Void Enqueue(DynamicObjectSnapshot item)%")) // item 450 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "HashSet<<unknown type>>" and m.getName() = "Add" and m.getStringSignature().matches("%Boolean Add(<unknown type> item)%")) // item 452 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "HashSet<<unknown type>>" and m.getName() = "Add" and m.getStringSignature().matches("%Boolean Add(<unknown type> item)%")) // item 453 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<AssessmentBase>" and m.getName() = "Insert" and m.getStringSignature().matches("%Void Insert(AssessmentBase item, Int32 index)%")) // item 467 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<AssessmentBase>" and m.getName() = "Remove" and m.getStringSignature().matches("%Boolean Remove(AssessmentBase item)%")) // item 468 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<AssessmentBase>" and m.getName() = "Remove" and m.getStringSignature().matches("%Boolean Remove(AssessmentBase item)%")) // item 469 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<GrabComponentsRequired>" and m.getName() = "Contains" and m.getStringSignature().matches("%Boolean Contains(GrabComponentsRequired item)%")) // item 471 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<HMDFocusButton>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(HMDFocusButton item)%")) // item 472 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<KeyValuePair<String,Object>>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(KeyValuePair<String,Object> item)%")) // item 473 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<KeyValuePair<String,Object>>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(KeyValuePair<String,Object> item)%")) // item 474 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<KeyValuePair<String,Object>>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(KeyValuePair<String,Object> item)%")) // item 475 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Generic" and m.getDeclaringType().getName() = "List<KeyValuePair<String,Object>>" and m.getName() = "Add" and m.getStringSignature().matches("%Void Add(KeyValuePair<String,Object> item)%")) // item 476 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "ToString" and m.getStringSignature().matches("%String ToString()%")) // item 488 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "ToString" and m.getStringSignature().matches("%String ToString()%")) // item 489 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "ToString" and m.getStringSignature().matches("%String ToString()%")) // item 490 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "ToString" and m.getStringSignature().matches("%String ToString()%")) // item 491 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "ToString" and m.getStringSignature().matches("%String ToString()%")) // item 492 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "ToString" and m.getStringSignature().matches("%String ToString()%")) // item 493 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "ToString" and m.getStringSignature().matches("%String ToString()%")) // item 494 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "ToString" and m.getStringSignature().matches("%String ToString()%")) // item 495 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "ToString" and m.getStringSignature().matches("%String ToString()%")) // item 496 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "Append" and m.getStringSignature().matches("%StringBuilder Append(String value)%")) // item 499 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "Append" and m.getStringSignature().matches("%StringBuilder Append(String value)%")) // item 500 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "Append" and m.getStringSignature().matches("%StringBuilder Append(String value)%")) // item 501 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "Append" and m.getStringSignature().matches("%StringBuilder Append(String value)%")) // item 502 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "Append" and m.getStringSignature().matches("%StringBuilder Append(String value)%")) // item 503 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "Append" and m.getStringSignature().matches("%StringBuilder Append(String value)%")) // item 504 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "Append" and m.getStringSignature().matches("%StringBuilder Append(String value)%")) // item 505 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "Append" and m.getStringSignature().matches("%StringBuilder Append(String value)%")) // item 506 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "Append" and m.getStringSignature().matches("%StringBuilder Append(Object value)%")) // item 579 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "Append" and m.getStringSignature().matches("%StringBuilder Append(Object value)%")) // item 580 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "Append" and m.getStringSignature().matches("%StringBuilder Append(Object value)%")) // item 581 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "Append" and m.getStringSignature().matches("%StringBuilder Append(Object value)%")) // item 582 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "Append" and m.getStringSignature().matches("%StringBuilder Append(Object value)%")) // item 583 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "Append" and m.getStringSignature().matches("%StringBuilder Append(Object value)%")) // item 584 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "AppendLine" and m.getStringSignature().matches("%StringBuilder AppendLine(String value)%")) // item 585 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "StringBuilder" and m.getName() = "AppendLine" and m.getStringSignature().matches("%StringBuilder AppendLine(String value)%")) // item 586 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "Encoding" and m.getName() = "GetByteCount" and m.getStringSignature().matches("%Int32 GetByteCount(String s)%")) // item 681 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "Encoding" and m.getName() = "GetByteCount" and m.getStringSignature().matches("%Int32 GetByteCount(String s)%")) // item 682 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "Encoding" and m.getName() = "GetBytes" and m.getStringSignature().matches("%Byte[] GetBytes(String s)%")) // item 683 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "Encoding" and m.getName() = "GetBytes" and m.getStringSignature().matches("%Byte[] GetBytes(String s)%")) // item 684 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "Encoding" and m.getName() = "GetBytes" and m.getStringSignature().matches("%Byte[] GetBytes(String s)%")) // item 685 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "Text" and m.getDeclaringType().getName() = "Encoding" and m.getName() = "GetBytes" and m.getStringSignature().matches("%Byte[] GetBytes(String s)%")) // item 686 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "File" and m.getName() = "Delete" and m.getStringSignature().matches("%Void Delete(String path)%")) // item 694 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "File" and m.getName() = "Delete" and m.getStringSignature().matches("%Void Delete(String path)%")) // item 695 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "File" and m.getName() = "Delete" and m.getStringSignature().matches("%Void Delete(String path)%")) // item 696 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "File" and m.getName() = "WriteAllBytes" and m.getStringSignature().matches("%Void WriteAllBytes(Byte[] bytes, String path)%")) // item 712 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "File" and m.getName() = "WriteAllBytes" and m.getStringSignature().matches("%Void WriteAllBytes(Byte[] bytes, String path)%")) // item 713 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "File" and m.getName() = "WriteAllBytes" and m.getStringSignature().matches("%Void WriteAllBytes(Byte[] bytes, String path)%")) // item 714 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "File" and m.getName() = "WriteAllBytes" and m.getStringSignature().matches("%Void WriteAllBytes(Byte[] bytes, String path)%")) // item 715 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "File" and m.getName() = "WriteAllBytes" and m.getStringSignature().matches("%Void WriteAllBytes(Byte[] bytes, String path)%")) // item 716 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "Stream" and m.getName() = "Seek" and m.getStringSignature().matches("%Int64 Seek(Int64 offset, SeekOrigin origin)%")) // item 733 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "Stream" and m.getName() = "Seek" and m.getStringSignature().matches("%Int64 Seek(Int64 offset, SeekOrigin origin)%")) // item 734 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "Stream" and m.getName() = "Seek" and m.getStringSignature().matches("%Int64 Seek(Int64 offset, SeekOrigin origin)%")) // item 735 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "Stream" and m.getName() = "Seek" and m.getStringSignature().matches("%Int64 Seek(Int64 offset, SeekOrigin origin)%")) // item 736 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "Stream" and m.getName() = "SetLength" and m.getStringSignature().matches("%Void SetLength(Int64 value)%")) // item 737 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "Stream" and m.getName() = "WriteByte" and m.getStringSignature().matches("%Void WriteByte(Byte value)%")) // item 738 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "TextWriter" and m.getName() = "Dispose" and m.getStringSignature().matches("%Void Dispose()%")) // item 814 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "TextWriter" and m.getName() = "Flush" and m.getStringSignature().matches("%Void Flush()%")) // item 815 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "Path" and m.getName() = "Combine" and m.getStringSignature().matches("%String Combine(String path1, String path2)%")) // item 816 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "Path" and m.getName() = "Combine" and m.getStringSignature().matches("%String Combine(String path1, String path2)%")) // item 817 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "Path" and m.getName() = "Combine" and m.getStringSignature().matches("%String Combine(String path1, String path2)%")) // item 818 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "Path" and m.getName() = "Combine" and m.getStringSignature().matches("%String Combine(String path1, String path2)%")) // item 819 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "Path" and m.getName() = "GetFileName" and m.getStringSignature().matches("%String GetFileName(String path)%")) // item 820 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "Path" and m.getName() = "GetFileName" and m.getStringSignature().matches("%String GetFileName(String path)%")) // item 821 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "IO" and m.getDeclaringType().getName() = "Path" and m.getName() = "GetFileName" and m.getStringSignature().matches("%String GetFileName(String path)%")) // item 822 role=taint-propagator
  or (m.getDeclaringType().getNamespace().getName() = "Threading" and m.getDeclaringType().getName() = "WaitHandle" and m.getName() = "WaitOne" and m.getStringSignature().matches("%Boolean WaitOne()%")) // item 873 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "Threading" and m.getDeclaringType().getName() = "WaitHandle" and m.getName() = "WaitOne" and m.getStringSignature().matches("%Boolean WaitOne()%")) // item 874 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "Threading" and m.getDeclaringType().getName() = "Mutex" and m.getName() = "ReleaseMutex" and m.getStringSignature().matches("%Void ReleaseMutex()%")) // item 875 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "Threading" and m.getDeclaringType().getName() = "Mutex" and m.getName() = "ReleaseMutex" and m.getStringSignature().matches("%Void ReleaseMutex()%")) // item 876 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "Threading" and m.getDeclaringType().getName() = "Thread" and m.getName() = "Start" and m.getStringSignature().matches("%Void Start(Object parameter)%")) // item 877 role=sink
  or (m.getDeclaringType().getNamespace().getName() = "RegularExpressions" and m.getDeclaringType().getName() = "Regex" and m.getName() = "Replace" and m.getStringSignature().matches("%String Replace(String input, String pattern, String replacement)%")) // item 886 role=taint-propagator
}
