module GeneratedAPIs {
  import csharp

  predicate isLLMDetectedSourceMethod(Method m) {
           m.getDeclaringType().getName() = "Assembly" and m.getName() = "GetType"
    or     m.getDeclaringType().getName() = "CustomAttributeExtensions" and m.getName() = "GetCustomAttribute<T>"
    or     m.getDeclaringType().getName() = "Dictionary<(String,TrackingControlType),VFAFloat>" and m.getName() = "TryGetValue"
    or     m.getDeclaringType().getName() = "Directory" and m.getName() = "CreateDirectory"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "First<GestureDriverBuilder>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "First<IEnumerable<<unknown type>>>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "First<RendererResult>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "FirstOrDefault<FeatureBuilder>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "FirstOrDefault<FixWriteDefaults>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "FirstOrDefault<OverrideMenuSettings>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "FirstOrDefault<SpsOptions>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "FirstOrDefault<T>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "FirstOrDefault<Type>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "FirstOrDefault<VFCondition>"
    or     m.getDeclaringType().getName() = "FeatureFinder" and m.getName() = "GetBuilder"
    or     m.getDeclaringType().getName() = "File" and m.getName() = "ReadAllBytes"
    or     m.getDeclaringType().getName() = "File" and m.getName() = "ReadAllText"
    or     m.getDeclaringType().getName() = "File" and m.getName() = "ReadLines"
    or     m.getDeclaringType().getName() = "GuidWrapperExtensions" and m.getName() = "Get`1"
    or     m.getDeclaringType().getName() = "LayerSourceService" and m.getName() = "GetSource"
    or     m.getDeclaringType().getName() = "MaterialExtensions" and m.getName() = "GetPropertyType"
    or     m.getDeclaringType().getName() = "RendererExtensions" and m.getName() = "GetBlendshapeName"
    or     m.getDeclaringType().getName() = "RendererExtensions" and m.getName() = "GetBlendshapeNames"
    or     m.getDeclaringType().getName() = "RendererExtensions" and m.getName() = "GetMutableMesh"
    or     m.getDeclaringType().getName() = "Stack<(<unknown type>,<unknown type>)>" and m.getName() = "Pop"
    or     m.getDeclaringType().getName() = "Stack<<unknown type>>" and m.getName() = "Pop"
    or     m.getDeclaringType().getName() = "VFController" and m.getName() = "GetLayer"
    or     m.getDeclaringType().getName() = "VRCFuryEditorUtils" and m.getName() = "GetResource`1"
    or     m.getDeclaringType().getName() = "VRCFuryEditorUtils" and m.getName() = "IsInRagdollSystem"
    or     m.getDeclaringType().getName() = "VRCFuryEditorUtils" and m.getName() = "LoadGuid`1"
    or     m.getDeclaringType().getName() = "VrcfObjectId" and m.getName() = "IdToObject`1"
  }

  predicate isLLMDetectedSinkMethod(Method m) {
        m.getDeclaringType().getName() = "Capture" and m.getName() = "ToString"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "First<Int32>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "First<Single>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "First<String>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Last<Int32>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Last<State>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Max<DepthAction>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Max<PlugDepthAction>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Min<DepthAction>"
    or     m.getDeclaringType().getName() = "Enumerator" and m.getName() = "MoveNext"
    or     m.getDeclaringType().getName() = "FieldInfo" and m.getName() = "GetValue"
    or     m.getDeclaringType().getName() = "FieldInfo" and m.getName() = "SetValue"
    or     m.getDeclaringType().getName() = "File" and m.getName() = "Create"
    or     m.getDeclaringType().getName() = "File" and m.getName() = "WriteAllBytes"
    or     m.getDeclaringType().getName() = "MethodBase" and m.getName() = "GetParameters"
    or     m.getDeclaringType().getName() = "MethodBase" and m.getName() = "Invoke"
    or     m.getDeclaringType().getName() = "PropertyInfo" and m.getName() = "GetValue"
    or     m.getDeclaringType().getName() = "Stream" and m.getName() = "Close"
  }

  predicate isLLMDetectedPropagator(Method m) {
        m.getDeclaringType().getName() = "AnchorOverrideFixBuilder" and m.getName() = "CreateEditor"
    or     m.getDeclaringType().getName() = "AnimationClipExtensions" and m.getName() = "EvaluateBlend"
    or     m.getDeclaringType().getName() = "AnimationClipExtensions" and m.getName() = "GetObjectCurves"
    or     m.getDeclaringType().getName() = "AnimationClipExtensions" and m.getName() = "HasMuscles"
    or     m.getDeclaringType().getName() = "AnimationClipExtensions" and m.getName() = "IsLooping"
    or     m.getDeclaringType().getName() = "AnimationClipExtensions" and m.getName() = "SetLooping"
    or     m.getDeclaringType().getName() = "AnimationRewriter" and m.getName() = "Combine"
    or     m.getDeclaringType().getName() = "AnimationRewriter" and m.getName() = "RewritePath"
    or     m.getDeclaringType().getName() = "AnimatorStateExtensions" and m.getName() = "VAddStateMachineBehaviour`1"
    or     m.getDeclaringType().getName() = "AnimatorStateMachineExtensions" and m.getName() = "VAddStateMachineBehaviour`1"
    or     m.getDeclaringType().getName() = "ApplyDuringUploadBuilder" and m.getName() = "CreateEditor"
    or     m.getDeclaringType().getName() = "ArmatureLinkBuilder" and m.getName() = "CreateEditor"
    or     m.getDeclaringType().getName() = "AudioLinkPlayModeRefreshHook" and m.getName() = "OnPreprocessAvatar"
    or     m.getDeclaringType().getName() = "Av3EmuAnimatorFixHook" and m.getName() = "OnPreprocessAvatar"
    or     m.getDeclaringType().getName() = "AvatarScaleBuilder" and m.getName() = "CreateEditor"
    or     m.getDeclaringType().getName() = "BlendShapeLinkBuilder" and m.getName() = "CreateEditor"
    or     m.getDeclaringType().getName() = "BlendTreeExtensions" and m.getName() = "RewriteParameters"
    or     m.getDeclaringType().getName() = "BlendshapeOptimizerBuilder" and m.getName() = "CreateEditor"
    or     m.getDeclaringType().getName() = "BlinkingBuilder" and m.getName() = "CreateEditor"
    or     m.getDeclaringType().getName() = "BulkUpgradeUtils" and m.getName() = "FindAll`1"
    or     m.getDeclaringType().getName() = "Dictionary<<unknown type>,(<unknown type>,Int32)>" and m.getName() = "TryGetValue"
    or     m.getDeclaringType().getName() = "Dictionary<<unknown type>,ISet<String>>" and m.getName() = "TryGetValue"
    or     m.getDeclaringType().getName() = "Dictionary<<unknown type>,List<String>>" and m.getName() = "TryGetValue"
    or     m.getDeclaringType().getName() = "Dictionary<<unknown type>,StoredEntry>" and m.getName() = "TryGetValue"
    or     m.getDeclaringType().getName() = "Dictionary<<unknown type>,VRCFuryHapticPlug>" and m.getName() = "TryGetValue"
    or     m.getDeclaringType().getName() = "Dictionary<String,VFABool>" and m.getName() = "TryGetValue"
    or     m.getDeclaringType().getName() = "Dictionary<String,VFAFloat>" and m.getName() = "TryGetValue"
    or     m.getDeclaringType().getName() = "Dictionary<String,VFCondition>" and m.getName() = "TryGetValue"
    or     m.getDeclaringType().getName() = "Dictionary<VRCFuryHapticPlug,BakeResult>" and m.getName() = "TryGetValue"
    or     m.getDeclaringType().getName() = "DisableLayerDrawer" and m.getName() = "CreatePropertyGUI"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Any<String>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Concat<FeatureModel>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Concat<String>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "DefaultIfEmpty<Int32>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "DefaultIfEmpty<Single>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Distinct<String>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "GroupBy<(String,String),String>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "OfType<BoundingBoxFix2>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "OfType<DirectTreeOptimizer>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "OfType<FixWriteDefaults>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "OfType<GestureDriverBuilder>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "OfType<Gizmo>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "OfType<MmdCompatibility>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "OfType<MoveMenuItem>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "OfType<ObjectToggleAction>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "OfType<OverrideMenuSettings>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "OfType<SecurityLockBuilder>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "OfType<SetIcon>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "OfType<SpsOptions>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "OfType<ToggleBuilder>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "OfType<TpsScaleFix>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "OrderBy<KeyValuePair<String,String>,String>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "OrderBy<T>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "OrderBy<Tuple<String,KeyValuePair<Type,Type>>,String>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Reverse<Int32>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<(<unknown type>,<unknown type>)>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<(<unknown type>,Nullable<<unknown type>>)>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<(<unknown type>,VFController),ControllerInfo>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<Assembly,Type>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<Char,Int32>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<DisableLayer,String>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<Exclude,String>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<FlipBookPage,State>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<GuidWrapper,String>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<IGrouping<String,(String,String)>,(String,String[])>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<Int32,SavedBlendshape>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<Int32,TResult>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<KeyValuePair<String,Single>,(<unknown type>,<unknown type>,String,Single)>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<KeyValuePair<String,String>,(<unknown type>,(String,String))>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<KeyValuePair<String,String>,(String,String)>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<KeyValuePair<Type,Type>,Tuple<String,KeyValuePair<Type,Type>>>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<LinkSkin>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<LinkTo>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<MuscleBindingType>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<Normalizer,IDictionary<String,String>>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<ObjectToggleAction>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<ParamsEntry>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<PendingClip>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<RendererResult>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<SecurityLockBuilder,VFCondition>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<SmoothParamEntry,String>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<String,(String,String)>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<String,String>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<String>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<T,Nullable<<unknown type>>>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<TResult>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<TrackingControlType,VFCondition>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<Tuple<String,KeyValuePair<Type,Type>>,KeyValuePair<Type,Type>>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<VFAFloat,(VFAFloatOrConst,Single)>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<VFAFloat,VFCondition>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Select<VFLayer>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "SelectMany<(Single,<unknown type>)>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "SelectMany<String,String>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "SelectMany<TResult>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "SelectMany<VRCFury,FeatureModel>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Take<String>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "ToArray<(<unknown type>,VFController)>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "ToArray<FeatureModel>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "ToArray<IDictionary<String,String>>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "ToArray<Int32>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "ToArray<SavedBlendshape>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "ToArray<String>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "ToArray<T>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "ToArray<TrackingControlType>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "ToArray<VFLayer>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "ToDictionary<TrackingControlType,TrackingControlType>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "ToList<SetIcon>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "ToList<State>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "ToList<String>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Where<(<unknown type>,Nullable<<unknown type>>)>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Where<(<unknown type>,VFController)>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Where<(String,String[])>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Where<Action>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Where<ControllerEntry>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Where<FeatureModel>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Where<Int32>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Where<MuscleBindingType>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Where<ObjectToggleAction>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Where<String>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Where<T>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Where<ToggleBuilder>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Where<TrackingControlType>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Where<Tuple<String,KeyValuePair<Type,Type>>>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Where<VFLayer>"
    or     m.getDeclaringType().getName() = "Enumerable" and m.getName() = "Zip`3"
    or     m.getDeclaringType().getName() = "EnumerableExtensions" and m.getName() = "NotNull`1"
    or     m.getDeclaringType().getName() = "ExcludeDrawer" and m.getName() = "CreatePropertyGUI"
    or     m.getDeclaringType().getName() = "FailureCheckEnd" and m.getName() = "OnPreprocessAvatar"
    or     m.getDeclaringType().getName() = "FailureCheckStart" and m.getName() = "OnPreprocessAvatar"
    or     m.getDeclaringType().getName() = "FlipbookAction" and m.getName() = "Upgrade"
    or     m.getDeclaringType().getName() = "GuidWrapper<<unknown type>>" and m.getName() = "Upgrade"
    or     m.getDeclaringType().getName() = "GuidWrapper<T>" and m.getName() = "Upgrade"
    or     m.getDeclaringType().getName() = "GuidWrapper`1" and m.getName() = "Upgrade"
    or     m.getDeclaringType().getName() = "HashSet<Single>" and m.getName() = "UnionWith"
    or     m.getDeclaringType().getName() = "HashSet<T>" and m.getName() = "Add"
    or     m.getDeclaringType().getName() = "HashSet<VFLayer>" and m.getName() = "Add"
    or     m.getDeclaringType().getName() = "HashSet<VRCFuryComponent>" and m.getName() = "UnionWith"
    or     m.getDeclaringType().getName() = "ImmutableHashSet" and m.getName() = "ToImmutableHashSet<(<unknown type>,(String,String))>"
    or     m.getDeclaringType().getName() = "ImmutableHashSet" and m.getName() = "ToImmutableHashSet<Int32>"
    or     m.getDeclaringType().getName() = "ImmutableHashSet" and m.getName() = "ToImmutableHashSet<MuscleBindingType>"
    or     m.getDeclaringType().getName() = "ImmutableHashSet" and m.getName() = "ToImmutableHashSet<String>"
    or     m.getDeclaringType().getName() = "ImmutableHashSet<<unknown type>>" and m.getName() = "Intersect"
    or     m.getDeclaringType().getName() = "IncludeDrawer" and m.getName() = "CreatePropertyGUI"
    or     m.getDeclaringType().getName() = "LayerSourceService" and m.getName() = "CopySource"
    or     m.getDeclaringType().getName() = "LegacyFeatureModel2" and m.getName() = "CreateNewInstance"
    or     m.getDeclaringType().getName() = "LinkSkinDrawer" and m.getName() = "CreatePropertyGUI"
    or     m.getDeclaringType().getName() = "LinkToDrawer" and m.getName() = "CreatePropertyGUI"
    or     m.getDeclaringType().getName() = "List<(<unknown type>,<unknown type>,Action<<unknown type>>)>" and m.getName() = "AddRange"
    or     m.getDeclaringType().getName() = "List<<unknown type>>" and m.getName() = "Add"
    or     m.getDeclaringType().getName() = "List<<unknown type>>" and m.getName() = "AddRange"
    or     m.getDeclaringType().getName() = "List<<unknown type>>" and m.getName() = "Insert"
    or     m.getDeclaringType().getName() = "List<<unknown type>>" and m.getName() = "Remove"
    or     m.getDeclaringType().getName() = "List<<unknown type>>" and m.getName() = "ToArray"
    or     m.getDeclaringType().getName() = "List<BindingRewrite>" and m.getName() = "Add"
    or     m.getDeclaringType().getName() = "List<FeatureModel>" and m.getName() = "Insert"
    or     m.getDeclaringType().getName() = "List<FieldInfo>" and m.getName() = "Add"
    or     m.getDeclaringType().getName() = "List<FlipBookPage>" and m.getName() = "Add"
    or     m.getDeclaringType().getName() = "List<Gesture>" and m.getName() = "Add"
    or     m.getDeclaringType().getName() = "List<MenuEntry>" and m.getName() = "Add"
    or     m.getDeclaringType().getName() = "List<NewFeatureModel>" and m.getName() = "Add"
    or     m.getDeclaringType().getName() = "List<Object>" and m.getName() = "Add"
    or     m.getDeclaringType().getName() = "List<Object>" and m.getName() = "ToArray"
    or     m.getDeclaringType().getName() = "List<PendingClip>" and m.getName() = "Add"
    or     m.getDeclaringType().getName() = "List<SetIcon>" and m.getName() = "Remove"
    or     m.getDeclaringType().getName() = "List<SetIcon>" and m.getName() = "ToArray"
    or     m.getDeclaringType().getName() = "List<SpsRewriteToDo>" and m.getName() = "Add"
    or     m.getDeclaringType().getName() = "List<State>" and m.getName() = "Add"
    or     m.getDeclaringType().getName() = "List<String>" and m.getName() = "AddRange"
    or     m.getDeclaringType().getName() = "List<T>" and m.getName() = "Add"
    or     m.getDeclaringType().getName() = "MaterialAction" and m.getName() = "Upgrade"
    or     m.getDeclaringType().getName() = "MmdCompatibilityBuilder" and m.getName() = "CreateEditor"
    or     m.getDeclaringType().getName() = "MotionExtensions" and m.getName() = "IsEmptyOrZeroLength"
    or     m.getDeclaringType().getName() = "MotionExtensions" and m.getName() = "IsStatic"
    or     m.getDeclaringType().getName() = "MoveMenuItemBuilder" and m.getName() = "CreateEditor"
    or     m.getDeclaringType().getName() = "OGBIntegrationBuilder" and m.getName() = "CreateEditor"
    or     m.getDeclaringType().getName() = "ObjectToggleAction" and m.getName() = "Upgrade"
    or     m.getDeclaringType().getName() = "OverrideMenuSettingsBuilder" and m.getName() = "CreateEditor"
    or     m.getDeclaringType().getName() = "ParallelEnumerable" and m.getName() = "AsParallel<Assembly>"
    or     m.getDeclaringType().getName() = "PlayerBuilt" and m.getName() = "OnPreprocessAvatar"
    or     m.getDeclaringType().getName() = "RemoveHandGesturesBuilder" and m.getName() = "CreateEditor"
    or     m.getDeclaringType().getName() = "RendererExtensions" and m.getName() = "GetVertexCount"
    or     m.getDeclaringType().getName() = "RendererExtensions" and m.getName() = "HasBlendshape"
    or     m.getDeclaringType().getName() = "SecurityLockBuilder" and m.getName() = "CreateEditor"
    or     m.getDeclaringType().getName() = "ShowInFirstPersonBuilder" and m.getName() = "CreateEditor"
    or     m.getDeclaringType().getName() = "Stack<<unknown type>>" and m.getName() = "Push"
    or     m.getDeclaringType().getName() = "Stack<Tuple<String[],<unknown type>>>" and m.getName() = "Pop"
    or     m.getDeclaringType().getName() = "VFLayer" and m.getName() = "Equals"
    or     m.getDeclaringType().getName() = "VFMultimap<A,B,HashSet<B>>" and m.getName() = "Get"
    or     m.getDeclaringType().getName() = "VFMultimap<A,B,List<B>>" and m.getName() = "Get"
    or     m.getDeclaringType().getName() = "VFMultimap`3" and m.getName() = "Get"
    or     m.getDeclaringType().getName() = "VFState" and m.getName() = "TransitionsTo"
    or     m.getDeclaringType().getName() = "VRCExpressionsMenuExtensions" and m.getName() = "RewriteParameters"
    or     m.getDeclaringType().getName() = "VRCFury" and m.getName() = "Upgrade"
    or     m.getDeclaringType().getName() = "VRCFuryComponentEditor<VRCFury>" and m.getName() = "CreateEditor"
    or     m.getDeclaringType().getName() = "VRCFuryComponentEditor<VRCFuryDebugInfo>" and m.getName() = "CreateEditor"
    or     m.getDeclaringType().getName() = "VRCFuryComponentEditor<VRCFuryGlobalCollider>" and m.getName() = "CreateEditor"
    or     m.getDeclaringType().getName() = "VRCFuryComponentEditor<VRCFuryHapticPlug>" and m.getName() = "CreateEditor"
    or     m.getDeclaringType().getName() = "VRCFuryComponentEditor<VRCFuryHapticSocket>" and m.getName() = "CreateEditor"
    or     m.getDeclaringType().getName() = "VRCFuryEditorUtils" and m.getName() = "GetPropertyType"
    or     m.getDeclaringType().getName() = "VRCFuryHapticPlugEditor" and m.getName() = "GetRenderers"
    or     m.getDeclaringType().getName() = "VRCFuryTestEditor" and m.getName() = "CreateEditor"
    or     m.getDeclaringType().getName() = "VfVisualElementExtensions" and m.getName() = "AlignItems`1"
    or     m.getDeclaringType().getName() = "VfVisualElementExtensions" and m.getName() = "FlexBasis`1"
    or     m.getDeclaringType().getName() = "VfVisualElementExtensions" and m.getName() = "FlexGrow`1"
    or     m.getDeclaringType().getName() = "VfVisualElementExtensions" and m.getName() = "MarginBottom`1"
    or     m.getDeclaringType().getName() = "VfVisualElementExtensions" and m.getName() = "OnClick`1"
    or     m.getDeclaringType().getName() = "VfVisualElementExtensions" and m.getName() = "PaddingLeft`1"
    or     m.getDeclaringType().getName() = "VfVisualElementExtensions" and m.getName() = "Row`1"
    or     m.getDeclaringType().getName() = "VfVisualElementExtensions" and m.getName() = "SetVisible`1"
    or     m.getDeclaringType().getName() = "VfVisualElementExtensions" and m.getName() = "Text`1"
    or     m.getDeclaringType().getName() = "VrcPreuploadHook" and m.getName() = "OnPreprocessAvatar"
    or     m.getDeclaringType().getName() = "WrappedCallback" and m.getName() = "OnPreprocessAvatar"
    or     m.getDeclaringType().getName() = "ZawooIntegrationBuilder" and m.getName() = "CreateEditor"
  }

}
